<?php

/**
 * Implements hook_init().
 */
function main_init() {
  drupal_add_js('http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenLite.min.js', 'external');
  drupal_add_js('http://cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js', 'external');
}

/**
 * Implements hook_block_info().
 */
function main_block_info() {
  $blocks = array();

  $blocks['main_menu_button'] = array(
    'info' => t('Main menu button'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['newsletter'] = array(
    'info' => t('Newsletter'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['social'] = array(
    'info' => t('Social'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['home_scroll_banner'] = array(
    'info' => t('Home scroll banner'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function main_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'main_menu_button':
      $block['content'] = theme('main_menu_button');
      break;
    case 'newsletter':
      $block['content'] = theme('newsletter');
      break;
    case 'social':
      $block['content'] = theme('social');
      break;
    case 'home_scroll_banner':
      $block['content'] = theme('home_scroll_banner');
      break;
  }
  return $block;
}

/**
 *  Implements hook_theme().
 */
function main_theme($existing, $type, $theme, $path) {
  return array(
    'main_menu_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'main_menu_button',
    ),
    'newsletter' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'newsletter',
    ),
    'social' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'social',
    ),
    'video_play_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'video_play_button',
    ),
    'home_scroll_banner' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'home_scroll_banner',
    ),
    'content_link_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'content_link_button',
    ),
  );
}

/**
 * Implements hook_node_view_alter().
 */
/**
 * Implements hook_node_view().
 */
function main_node_view($node, $view_mode, $langcode) {
  switch($node->type) {
    case 'home_page':
      if (!empty($node->field_home_video)) {
        $node->content['field_headline']['#suffix'] = theme('video_play_button');
      }
      break;
    case 'content_page':
      if ($view_mode == 'teaser') {
        $node->content['button'] = array(
          '#markup' => theme('content_link_button'),
          '#weight' => 10,
        );
      }
      break;
  }
}

function main_preprocess_node(&$variables) {
  switch ($variables['type']) {
    case 'content_page':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;
      break;
  }
}