<?php

/**
 * Implements hook_block_info().
 */
function main_block_info() {
  $blocks = array();

  $blocks['home_push'] = array(
    'info' => t('Home push'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function main_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'home_push':

      $block['content'] = theme('social_share');
      break;
  }
  return $block;
}

/**
 *  Implements hook_theme().
 */
function main_theme($existing, $type, $theme, $path) {
  return array(
//    'social_links' => array(
//      'path' => drupal_get_path('module', 'main') . '/templates',
//      'template' => 'social_links',
//    ),
  );
}