<?php

/**
 * Implements hook_init().
 */
function main_init() {
  drupal_add_js('http://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenLite.min.js', 'external');
  drupal_add_js('http://cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js', 'external');
}

/**
 * Implements hook_block_info().
 */
function main_block_info() {
  $blocks = array();

  $blocks['main_menu_button'] = array(
    'info' => t('Main menu button'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['newsletter'] = array(
    'info' => t('Newsletter'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['social'] = array(
    'info' => t('Social'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['home_scroll_banner'] = array(
    'info' => t('Home scroll banner'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['footer_legals'] = array(
    'info' => t('Footer legals'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['prehome_cup'] = array(
    'info' => t('Prehome cup'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function main_block_view($delta) {
  global $language;
  $block = array();
  switch ($delta) {
    case 'main_menu_button':
      $block['content'] = theme('main_menu_button');
      break;
    case 'newsletter':
      $block['content'] = theme('newsletter');
      break;
    case 'social':
      $block['content'] = theme('social');
      break;
    case 'home_scroll_banner':
      $block['content'] = theme('home_scroll_banner', array('url' => drupal_get_path_alias('node/5', $language->language)));
      break;
    case 'footer_legals':
      $block['content'] = theme('footer_legals');
      break;
    case 'prehome_cup':
      $items = array(
        t('Discover all the secrets of tea.'),
      );
      $texts = theme('item_list', array('items' => $items));
      $block['content'] = theme('prehome_cup', array('texts' => $texts, 'call' => t('Shake your curiosity')));
      break;
  }
  return $block;
}

/**
 *  Implements hook_theme().
 */
function main_theme($existing, $type, $theme, $path) {
  return array(
    'main_menu_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'main_menu_button',
    ),
    'newsletter' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'newsletter',
    ),
    'social' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'social',
    ),
    'video_play_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'video_play_button',
    ),
    'scroll_down_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'scroll_down_button',
    ),
    'home_scroll_banner' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'home_scroll_banner',
      'url' => '',
    ),
    'content_link_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'content_link_button',
    ),
    'footer_legals' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'footer_legals',
    ),
    'close_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'close_button',
    ),
    'bullet_button' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'bullet_button',
    ),
    'contact_link' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'contact_link',
      'url' => '',
    ),
    'prehome_cup' => array(
      'path' => drupal_get_path('module', 'main') . '/templates',
      'template' => 'prehome_cup',
      'texts' => '',
      'call' => '',
    ),
  );
}

/**
 * Implements hook_node_view_alter().
 */
/**
 * Implements hook_node_view().
 */
function main_node_view($node, $view_mode, $langcode) {
  global $language;

  switch($node->type) {
    case 'home_page':
      if (!empty($node->field_home_video)) {
        $node->content['field_headline']['#suffix'] = theme('video_play_button');
      }
      break;
    case 'content_page':
      if ($view_mode == 'full') {
        $node->content['field_banner']['#prefix'] = '<div id="banner-wrapper">' . theme('scroll_down_button');
        $node->content['field_banner']['#suffix'] = '</div>';

        // La plante
        if ($node->nid == 6) {
          $nodes = main_load_nodes('tea_type');
          $markup = '';
          foreach($nodes as $element) {
            $item = node_view($element);
            $markup .= render($item);
          }
          $node->content['tea_types'] = array(
            '#markup' => $markup,
            '#prefix' => '<div id="tea-types-wrapper"><div id="section-title">' . t('Main tea types') . '</div><div id="tea-types">',
            '#suffix' => '</div></div>',
            '#weight' => 2,
          );
          $node->content['#group_children']['tea_types'] = 'group_specific_content';
        }

        // Thé dans le monde (carte)
        if ($node->nid == 7) {
          $nodes = main_load_nodes('map_country');
          $markup = '';
          foreach($nodes as $element) {
            $item = node_view($element);
            $markup .= render($item);
          }
          $node->content['map_countries'] = array(
            '#markup' => $markup,
            '#prefix' => '<div id="map-countries-wrapper"><div id="section-title">' . t('Twinings around the world') . '</div><div id="map-countries">',
            '#suffix' => '</div></div>',
            '#weight' => 2,
          );
        }

        $menu = menu_link_get_preferred(current_path());
        switch($menu['p1']) {
          case 437:
            $menu_parent_title = t('Discovery');
            break;
          case 455:
            $menu_parent_title = t('Tea like Twinings');
            break;
        }
        if (isset($menu_parent_title) && $menu['p1'] !== $menu['mlid']) {
          $node->content['title_field']['#prefix'] = '<div id="menu-parent-title">' . $menu_parent_title . '</div>';
        }
      }
      if ($view_mode == 'teaser') {
        $node->content['button'] = array(
          '#markup' => theme('content_link_button'),
          '#weight' => 10,
        );
        $node->content['links']['node']['#links']['node-readmore']['title'] = '';
      }
      break;
    case 'products_page':
      if ($view_mode == 'full') {
        $node->content['field_banner']['#prefix'] = '<div id="banner-wrapper">' . theme('scroll_down_button');
        $node->content['field_banner']['#suffix'] = '</div>';
      }
      if ($view_mode == 'teaser') {
        $node->content['button'] = array(
          '#markup' => theme('content_link_button'),
          '#weight' => 10,
        );
        $node->content['links']['node']['#links']['node-readmore']['title'] = '';
      }
      break;
    case 'product':
      if ($view_mode == 'teaser') {
        $node->content['links']['node']['#links']['node-readmore']['title'] = '';
      }
      if ($view_mode == 'full') {
        $node->content['scroll_down_button']['#markup'] = theme('scroll_down_button');
        $node->content['#group_children']['scroll_down_button'] = 'group_features';
      }
      break;
    case 'page':
      if ($view_mode == 'full') {
        //Contact
        if ($node->nid == 15) {
          $form = drupal_get_form('main_contact_form');
          $node->content['contact_form']['#markup'] = drupal_render($form);
        }

        //Nous trouver
        if ($node->nid == 16) {
          $url = drupal_get_path_alias('node/15', $language->language);
          $node->content['contact_link']['#markup'] = '<div id="link-wrapper">' . theme('contact_link', array('url' => $url)) . '</div>';
          $node->content['contact_link']['#weight'] = 10;
        }
      }
      break;
    case 'map_country':
      if ($view_mode == 'full') {
        $node->content['popup-title']['#markup'] = '<div id="popup-title">' . $node->title_field[$language->language][0]['value'] . '</div>';
        $node->content['#group_children']['popup-title'] = 'group_map_popup';
      }
  }
}

function main_preprocess_node(&$variables) {
  switch ($variables['type']) {
    case 'content_page':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;

      $menu = menu_link_get_preferred(current_path());
      if ($menu['plid'] == 0) {
        $variables['classes_array'][] = 'parent';
      }
      switch($menu['p1']) {
        case 437:
          $variables['classes_array'][] = 'category-la-decouverte';
          $variables['menu_parent_title'] = t('Discovery');
          break;
        case 455:
          $variables['classes_array'][] = 'category-the-comme-twinings';
          $variables['menu_parent_title'] = t('Tea like Twinings');
          break;
      }
      break;
    case 'product':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;
      $term = taxonomy_term_load($variables['field_theme_variation'][LANGUAGE_NONE][0]['tid']);
      $variables['attributes_array']['data-colour'] = $term->field_colour[LANGUAGE_NONE][0]['value'];
      $variables['attributes_array']['data-pattern'] = file_create_url($term->field_pattern[LANGUAGE_NONE][0]['uri']);
      if (isset($variables['field_intensity'][0])) {
        $term = taxonomy_term_load($variables['field_intensity'][0]['tid']);
        $variables['classes_array'][] = strtolower($term->name_field['en'][0]['value']) . '-intensity';
      }
      break;
    case 'products_page':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;
      break;
    case 'tea_type':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;
      break;
    case 'map_country':
      $variables['page'] = TRUE;
      $variables['display_submitted'] = FALSE;
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function main_preprocess_entity(&$variables) {
  if ($variables['entity_type'] == 'information_board') {
    $variables['page'] = TRUE;
    $variables['display_submitted'] = FALSE;
  }

  if ($variables['entity_type'] == 'information_boards_group') {
    $variables['page'] = TRUE;
    $variables['display_submitted'] = FALSE;
  }

  if ($variables['entity_type'] == 'bullet_popup') {
    $variables['page'] = TRUE;
    $variables['display_submitted'] = FALSE;
  }

  if ($variables['entity_type'] == 'frieze_element') {
    $variables['page'] = TRUE;
    $variables['display_submitted'] = FALSE;
    if (isset($variables['elements']['#entity']->field_text_position[LANGUAGE_NONE][0])) {
      $variables['classes_array'][] = 'text-on-the-' . $variables['elements']['#entity']->field_text_position[LANGUAGE_NONE][0]['value'];
    }
  }

  if ($variables['entity_type'] == 'frieze') {
    $variables['page'] = TRUE;
    $variables['display_submitted'] = FALSE;
  }
}

/**
 * Implements hook_form_alter().
 */
function main_form_alter(&$form, &$form_state, $form_id) {
  switch($form['#id']) {
    case 'views-exposed-form-products-default':
      if (isset($form['field_category_tid']['#options']['All'])) {
        unset($form['field_category_tid']['#options']['All']);
      }
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function main_preprocess_views_view(&$vars) {
  global $language;

  $view = $vars['view'];
  if ($view->name == 'products' && isset($view->exposed_raw_input['field_category_tid'])) {
    $tid = $view->exposed_raw_input['field_category_tid'];
    $term = taxonomy_term_load($tid);
    $label = $term->field_products_page_label[$language->language][0]['value'];

    $vars['product_category_label'] = $label;
  }
}

/**
 * Implements hook_entity_view().
 */
function main_entity_view($entity, $type, $view_mode, $langcode) {
  global $language;

  switch($type){
    case 'information_board':
      $entity->content['#groups']['group_content']->label = ' ';
      break;
    case 'bullet_popup':
      $entity->content['close_button']['#markup'] = theme('close_button');
      $entity->content['#group_children']['close_button'] = 'group_popup';
      $entity->content['bullet_button']['#markup'] = theme('bullet_button');
      $entity->content['#group_children']['bullet_button'] = 'group_button';
      break;
  }
}

/**
 * @param $fields
 * @param $context
 */
function main_inline_entity_form_table_fields_alter(&$fields, $context) {
  if ($context['parent_bundle'] == 'content_page' && $context['entity_type'] == 'information_boards_group') {
    unset($fields['id']);

    $fields['title_field'] = array(
      'type' => 'field',
      'label' => t('Title'),
      'weight' => 2
    );
  }

  if ($context['entity_type'] == 'bullet_popup') {
    unset($fields['id']);

    $fields['title_field'] = array(
      'type' => 'field',
      'label' => t('Title'),
      'weight' => 2
    );
  }

  if ($context['parent_bundle'] == 'information_boards_group' && $context['entity_type'] == 'information_board') {
    unset($fields['id']);

    $fields['field_picto'] = array(
      'type' => 'field',
      'label' => t('Image'),
      'weight' => 1
    );

    $fields['title_field'] = array(
      'type' => 'field',
      'label' => t('Title'),
      'weight' => 2
    );
  }
}

function main_load_nodes($type) {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type)
    ->propertyCondition('status', NODE_PUBLISHED)
    ->addMetaData('account', user_load(1)); // Run the query as user 1.

  $result = $query->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    $items = entity_load('node', $nids);
  }

  return $items;
}

function main_contact_form($form, $form_state) {

  $form['top_block'] = array(
    '#type' => 'container',
  );

  $form['top_block']['last_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Last name') . '*'),
  );

  $form['top_block']['first_name'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('First name') . '*'),
  );

  $form['top_block']['email'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Email') . '*'),
  );

  $form['top_block']['phone'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Phone') . '*'),
  );

  $form['top_block']['address'] = array(
    '#type' => 'textfield',
    '#attributes' => array('placeholder' => t('Address')),
  );

  $form['top_block']['city'] = array(
    '#type' => 'textfield',
    '#attributes' => array('placeholder' => t('City')),
  );

  $form['top_block']['post_code'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Post code') . '*'),
  );

  $form['top_block']['birthday'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'd/m/Y',
    '#attributes' => array('placeholder' => t('Birthday')),
  );

  $form['top_block']['message'] = array(
    '#type' => 'textarea',
    '#required' => TRUE,
    '#attributes' => array('placeholder' => t('Message') . '*'),
  );

  $form['top_block']['captcha'] = array(
    '#type' => 'captcha',
    '#captcha_type' => 'recaptcha/reCAPTCHA',
  );

  $form['bottom_block'] = array(
    '#type' => 'container',
  );

  $form['bottom_block']['actions'] = array(
    '#type' => 'container',
  );

  $form['bottom_block']['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  $form['#submit'][] = 'main_contact_form_submit';

  return $form;
}

function main_contact_form_submit($form, $form_state) {
  drupal_set_message(t('Your message has been taken into account. We will get back to you via email shortly.'));
//  $mail_to = variable_get('site_mail', '');
  $mail_to = 'sebastien@lumini.fr';
  drupal_mail(
    'main',
    'contact',
    $mail_to,
    language_default(),
    array(
      'values' => $form_state['values'],
    )
  );
}

function main_mail($key, &$message, $params) {
  switch ($key) {
    case 'contact':
      $message['subject'] = variable_get('site_name') . ' : ' . t('Contact message');
      $message['body'][] = t('@first_name @last_name (@email) sent a message: ', array(
        '@first_name' => $params['values']['first_name'],
        '@last_name' => $params['values']['last_name'],
        '@email' => $params['values']['email']
      ));
      $message['body'][] = $params['values']['message'];
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function main_preprocess_page(&$variables) {
  if (isset($variables['node']) && $variables['node']->nid == 3) {
    drupal_goto('/node/16');
  }
}